add token verification for cloudflare

diff --git a/ddnsbot b/ddnsbot
--- a/ddnsbot
+++ b/ddnsbot
@@ -38,7 +38,6 @@ LC_ALL=C
 DDNSBOT_PRGNAM="ddnsbot"
 DDNSBOT_VERSION='0.0.42'
 DDNSBOT_VERBOSITY=${DDNSBOT_VERBOSITY:-0}
-DDNSBOT_IP_VERSION=${DDNSBOT_IP_VERSION:-0}
 
 DDNSBOT_PUBLIC_IP_SERVERS_4="
 https://ipv4.seeip.org
@@ -84,12 +83,21 @@ EOF
 )
 
 err() (
-  printf >&2 'ERROR: %s\n' "$*"
+  datestamp="$(TZ=UTC date +%Y-%m-%dT%TZ)"
+  printf >&2 '[%s] ERROR: %s\n' "$datestamp" "$*"
 )
 
 inf() (
-  if [ $DDNSBOT_VERBOSITY -gt 0 ]; then
-    printf >&2 %s\\n "$*"
+  if [ "$DDNSBOT_VERBOSITY" -gt 0 ]; then
+    datestamp="$(TZ=UTC date +%Y-%m-%dT%TZ)"
+    printf >&2 '[%s] %s\n' "$datestamp" "$*"
+  fi
+)
+
+warn() (
+  if [ "$DDNSBOT_VERBOSITY" -gt 0 ]; then
+    datestamp="$(TZ=UTC date +%Y-%m-%dT%TZ)"
+    printf >&2 '[%s] WARN: %s\n' "$datestamp" "$*"
   fi
 )
 
@@ -141,11 +149,14 @@ dependency_check() (
   return "$retval"
 )
 
-zones_from_domain() (
+get_zones_from_domain() (
   # Usage: <domain.tld>
   # Returns: List of possible zone names derived from domain
   # Example: zones_from_domain my.example.com returns: com example.com my.example.com
   domain="${1?zones_from_domain: no domain specified}"
+  case "$domain" in
+    *:*) printf %s\\n "${domain%:*}" ; return ;;
+  esac
   zones=""
   while true; do
     domain=${domain#*.}
@@ -168,7 +179,7 @@ ddnsbot_get_public_ip() (
 		if ! res=$(http__curl \
 			--connect-timeout 10 \
 			--url "$ip" 2>&1); then
-		  err "$res"
+		  warn "$res"
 	  else
 		  printf %s\\n "$res"
 		  return 0
@@ -179,8 +190,76 @@ ddnsbot_get_public_ip() (
 
 )
 
+cloudflare__verify_token() (
+  # Receives: Token string or file path
+  # Checks for dns_cloudflare_api_token
+  # Note: using a global api key is not currently supported
+  if [ -f "$1" ]; then
+    while read -r line; do
+      case "$line" in
+        \#*) continue ;; # skip commented lines
+        dns_cloudflare_api_token*=*)
+          token="${line##*=}"
+          # strip leading and trailing spaces
+          token="${token#*\ }"
+          token="${token%\ *}"
+          break
+          ;;
+        *) continue ;;
+      esac
+    done < "$1"
+    if [ -z "${token:-}" ]; then
+      printf "No matching key from file %s\n" "$1"
+      return 1
+    fi
+  else
+    # if not a file, must be a string
+    token="$1"
+  fi
+
+  # verify token
+  if ! verify_json="$(http__curl \
+    --request GET \
+    --url https://api.cloudflare.com/client/v4/user/tokens/verify \
+    --header "Authorization: Bearer $token" \
+    --header "Content-Type: application/json")"; then
+    printf %s\\n "$verify_json"
+    return 1
+  fi
+
+  # Confirm the JSON was successful
+  success="$(printf %s\\n "$verify_json" | jq -r .success)"
+  case "$success" in
+    true) printf %s\\n "$token" ;; # if true
+       *) printf %s\\n "$verify_json" ; return 1 ;; # if anything else
+  esac
+
+)
+
+cloudflare__get_zone_id() (
+  # Check for args
+  if [ $# -eq 0 ]; then
+    printf 'Improper use of cloudflare__get_zone_id'
+    return 1
+  fi
+
+  # Parse args
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -z) zone_name="$2" ; shift 2 ;;
+      -T) token="$2" ; shift 2 ;;
+       *) printf 'Illegal argument: %s\n' "$1" ; return 1 ;;
+    esac
+  done
+
+  # DEBUG
+  echo "1234567890"
+)
+
 main() {
 
+  ddnsbot_ip_version=0
+  
   # dependency check
   dependencies="curl jq"
   if ! check=$(dependency_check "$dependencies"); then
@@ -219,8 +298,8 @@ main() {
     -*) # parse bool flags
       while getopts :46v bool; do
         case "$bool" in
-          4) DDNSBOT_IP_VERSION=$((DDNSBOT_IP_VERSION + 4)) ;;
-          6) DDNSBOT_IP_VERSION=$((DDNSBOT_IP_VERSION + 6)) ;;
+          4) ddnsbot_ip_version=$((ddnsbot_ip_version + 4)) ;;
+          6) ddnsbot_ip_version=$((ddnsbot_ip_version + 6)) ;;
           v) DDNSBOT_VERBOSITY=$((DDNSBOT_VERBOSITY + 1)) ;;
           *)
             usage
@@ -243,11 +322,11 @@ main() {
 
   # Set DDNSBOT_PUBLIC_IP_URL
   if [ -z "${public_ip_reflector:-}" ]; then
-    if [ $DDNSBOT_IP_VERSION -le 4 ]; then
+    if [ $ddnsbot_ip_version -le 4 ]; then
       public_ip_reflector="$DDNSBOT_PUBLIC_IP_SERVERS_4"
-    elif [ $DDNSBOT_IP_VERSION -eq 6 ]; then
+    elif [ $ddnsbot_ip_version -eq 6 ]; then
       public_ip_reflector="$DDNSBOT_PUBLIC_IP_SERVERS_6"
-    elif [ $DDNSBOT_IP_VERSION -ge 10 ]; then
+    elif [ $ddnsbot_ip_version -ge 10 ]; then
       public_ip_reflector="$DDNSBOT_PUBLIC_IP_SERVERS_6 \
         $DDNSBOT_PUBLIC_IP_SERVERS_4"
     fi
@@ -271,12 +350,57 @@ main() {
   fi
 
   printf 'Public IP Address: %s\n' "$public_ip_address"
-  return
 
-  if ! ret=$(cmd_"$command"); then
-		err "$ret"
-		return 1
-	fi
+  if [ -z "${domains:-}" ]; then
+    inf "No domains specified."
+    return
+  fi
+
+  if [ -z "${dns_api_plugin:-}" ]; then
+    err "No DNS plugin specified."
+    return 1
+  fi
+
+  if [ -z "${dns_api_token:-}" ]; then
+    err "No DNS API Token."
+    return 1
+  fi
+
+  # Get the string for the token
+  if ! dns_api_token="$("${dns_api_plugin}"__verify_token "$dns_api_token")"; then
+    err "Unable to initialize DNS API Token with $dns_api_plugin."
+    warn "$dns_api_token"
+    return 1
+  fi
+
+  # Process the domain
+  for d in $domains; do
+    if ! zone_list="$(get_zones_from_domain "$d")"; then
+      err "Unable to get zones from $d"
+      return 1
+    fi
+    
+    # Drop the zone if specificed in the domain
+    case "$zone_list" in
+      *:*) d="${d#*:}" ;;
+    esac
+
+    for z in $zone_list; do
+      if dns_zone_id="$("${dns_api_plugin}"__get_zone_id \
+        -z "$z" -T "$dns_api_token")"; then
+        inf "Found zone id for $z: $dns_zone_id"
+        break
+      else
+        dns_zone_id=""
+      fi
+    done
+
+    if [ -z "${dns_zone_id:-}" ]; then
+      err "Unable to get zone ID for $d"
+      return 1
+    fi
+
+  done # end of $domains loop
 }
 
 main "$@"
